# Generated by Django 5.2.10 on 2026-01-20 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('CUSTOMER', 'Customer'), ('SHOP', 'Shop Owner'), ('STAFF', 'Staff'), ('ADMIN', 'Admin')], default='CUSTOMER', max_length=10),
        ),
    ]
