# Generated by Django 4.2.30 on 2026-08-14 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_userprofile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_shop_owner',
            field=models.BooleanField(default=False, help_text='User also owns shops (dual role: Customer + Shop Owner)'),
        ),
    ]
