# Generated by Django 5.2.10 on 2026-01-19 11:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=300)),
                ('phone', models.CharField(max_length=15)),
                ('is_verified', models.BooleanField(default=False)),
                ('qr_code', models.CharField(editable=False, max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('a4_bw_price', models.DecimalField(decimal_places=2, default=1.0, max_digits=6)),
                ('a4_color_price', models.DecimalField(decimal_places=2, default=5.0, max_digits=6)),
                ('a3_bw_price', models.DecimalField(decimal_places=2, default=2.0, max_digits=6)),
                ('a3_color_price', models.DecimalField(decimal_places=2, default=10.0, max_digits=6)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shop', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
