# Generated by Django 5.2.10 on 2026-01-19 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0002_shop_avg_print_time_shop_commission_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='suspension_reason',
            field=models.TextField(blank=True),
        ),
    ]
