# Generated by Django 5.2.10 on 2026-01-20 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0004_shopimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='closing_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='opening_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
