# Generated by Django 5.2.10 on 2026-01-20 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0005_shop_closing_time_shop_opening_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='paid_total',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Total amount already paid out to shop', max_digits=10),
        ),
        migrations.AlterField(
            model_name='shop',
            name='earnings_total',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Lifetime gross earnings', max_digits=10),
        ),
    ]
