# Generated by Django 4.2.30 on 2026-08-14 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PayoutConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payout_enabled', models.BooleanField(default=False)),
                ('payout_hour', models.IntegerField(default=6, help_text='Hour to run payouts (0-23)')),
                ('payout_minute', models.IntegerField(default=0, help_text='Minute to run payouts (0-59)')),
                ('payout_mode', models.CharField(choices=[('NEFT', 'NEFT'), ('RTGS', 'RTGS'), ('IMPS', 'IMPS'), ('UPI', 'UPI')], default='IMPS', max_length=10)),
                ('payout_days', models.CharField(default='0,1,2,3,4,5,6', help_text='Comma-separated day numbers (0=Monday, 6=Sunday)', max_length=50)),
                ('razorpayx_account_number', models.CharField(blank=True, help_text='RazorpayX business account number for debiting', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Payout Configuration',
                'verbose_name_plural': 'Payout Configuration',
            },
        ),
    ]
