# Generated by Django 5.2.10 on 2026-01-19 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(blank=True, max_length=100)),
                ('customer_phone', models.CharField(max_length=15)),
                ('file', models.FileField(upload_to='uploads/')),
                ('file_name', models.CharField(max_length=255)),
                ('pages_count', models.IntegerField()),
                ('paper_size', models.CharField(choices=[('A4', 'A4'), ('A3', 'A3')], default='A4', max_length=2)),
                ('color_type', models.CharField(choices=[('BW', 'Black & White'), ('COLOR', 'Color')], default='BW', max_length=10)),
                ('print_side', models.CharField(choices=[('SINGLE', 'Single Side'), ('DOUBLE', 'Double Side')], default='SINGLE', max_length=10)),
                ('price_per_page', models.DecimalField(decimal_places=2, max_digits=6)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Payment'), ('PAID', 'Paid'), ('ACCEPTED', 'Accepted by Shop'), ('PRINTING', 'Printing'), ('READY', 'Ready for Pickup'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('REJECTED', 'Rejected by Shop')], default='PENDING', max_length=20)),
                ('pin_code', models.CharField(blank=True, max_length=4, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='shops.shop')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
