# Generated by Django 5.2.10 on 2026-01-19 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_commission_amount_order_completed_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='price_per_page',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
