# Generated by Django 5.2.10 on 2026-01-19 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_price_per_page_alter_order_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='object_id',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
