# Generated by Django 5.2.10 on 2026-01-19 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_auditlog_object_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='copies',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
