# Generated by Django 5.2.10 on 2026-01-19 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_copies'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='final_sheets',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='pages_per_sheet',
            field=models.IntegerField(choices=[(1, '1 page per sheet'), (2, '2 pages per sheet'), (4, '4 pages per sheet'), (6, '6 pages per sheet'), (9, '9 pages per sheet')], default=1),
        ),
        migrations.AddField(
            model_name='order',
            name='print_type',
            field=models.CharField(choices=[('ALL', 'All pages'), ('ODD', 'Odd pages only'), ('EVEN', 'Even pages only')], default='ALL', max_length=10),
        ),
        migrations.AddField(
            model_name='order',
            name='special_note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
