# Generated by Django 5.2.10 on 2026-01-19 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_final_sheets_order_pages_per_sheet_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='color_type',
        ),
        migrations.RemoveField(
            model_name='order',
            name='copies',
        ),
        migrations.RemoveField(
            model_name='order',
            name='file',
        ),
        migrations.RemoveField(
            model_name='order',
            name='file_name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='pages_count',
        ),
        migrations.RemoveField(
            model_name='order',
            name='pages_per_sheet',
        ),
        migrations.RemoveField(
            model_name='order',
            name='paper_size',
        ),
        migrations.RemoveField(
            model_name='order',
            name='price_per_page',
        ),
        migrations.RemoveField(
            model_name='order',
            name='print_side',
        ),
        migrations.RemoveField(
            model_name='order',
            name='print_type',
        ),
        migrations.RemoveField(
            model_name='order',
            name='special_note',
        ),
        migrations.CreateModel(
            name='OrderFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/orders/')),
                ('file_name', models.CharField(max_length=255)),
                ('file_size_mb', models.FloatField(default=0.0)),
                ('pages_count', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paper_size', models.CharField(choices=[('A4', 'A4'), ('A3', 'A3')], default='A4', max_length=2)),
                ('color_type', models.CharField(choices=[('BW', 'Black & White'), ('COLOR', 'Color')], default='BW', max_length=10)),
                ('print_side', models.CharField(choices=[('SINGLE', 'Single Side'), ('DOUBLE', 'Double Side')], default='SINGLE', max_length=10)),
                ('pages_per_sheet', models.IntegerField(choices=[(1, '1 page per sheet'), (2, '2 pages per sheet'), (4, '4 pages per sheet'), (6, '6 pages per sheet'), (9, '9 pages per sheet')], default=1)),
                ('print_type', models.CharField(choices=[('ALL', 'All pages'), ('ODD', 'Odd pages only'), ('EVEN', 'Even pages only')], default='ALL', max_length=10)),
                ('copies', models.PositiveIntegerField(default=1)),
                ('special_note', models.TextField(blank=True, null=True)),
                ('price_per_sheet', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('final_sheets', models.IntegerField(default=0)),
                ('total_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='orders.order')),
            ],
        ),
    ]
