# Generated by Django 5.2.10 on 2026-01-20 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_remove_order_color_type_remove_order_copies_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shop_proof_image',
            field=models.ImageField(blank=True, null=True, upload_to='order_proofs/'),
        ),
    ]
